language: java

jdk:
#  - oraclejdk8
#  - oraclejdk11
#  - oraclejdk13
#  - openjdk8
  - openjdk11
#  - openjdk13

addons:
  sonarcloud:
    organization: jinahya-github
    token: ${SONAR_TOKEN}
    branches:
      - develop
      - master

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
